### ISSUE TITLE
Unable to download the GCP as shapefile

### ISSUE THREAD

**Issue by flandsberg** [openforis/accuracy-assessment#1]
Hi,

I was hoping to download the stratified random sample on the map but it gives me an error message.

Thanks,

Florence

**Comment by lecrabe** [comment]
Hi Florence,

Thanks for using and testing.
A couple of checks:
- Did you use the version from the github directly or did you clone the application ?
- Could you give more details on what went wrong ? Can you tell me what the error message is ?
- Did you install Rtools and add the path as indicated on the readme page? That has been occurring several times and you need those to zip files.

Let know
Remi

**Comment by flandsberg** [comment]
Hi Remi,

I am an ignoramus so I am not sure I can answer your questions….

Thanks for being so responsive!

Florence

**Comment by lecrabe** [comment]
Hi Florence,

Again, thanks for testing

I think you are right and maybe it makes things too complicated to ask people to change the variable in their local paths, and it requires admin rights which may be problematic.

So, I changed the code to access the Rtools directly. Could you try again ?

Thanks!

**Comment by flandsberg** [comment]
Hi,

I did download this but didn’t change the local paths. Do you want me to re-download it? Sorry, I am really out of my area of expertise…

Thanks,

Florence

**Comment by lecrabe** [comment]
Hi Florence,

No worries

Normally if you have downloaded and installed the Rtools, you shouldn't need to change the path anymore I modified the code in that sense.

Could you simply try the application and let me know if  ti works ?

If you want, you can contact me directly by email or by skype at rdannunzio.
Rémi

**Comment by flandsberg** [comment]
Hi Remi,

Well, it worked better: I don’t have the 404 error message but I don’t find the zipped file. I tried to save it in different places and it didn’t work. We can do share screens if you want (I just send you an invitation on Skype).

Cheers and many thanks for your support!

Florence

**Comment by lecrabe** [comment]
The problem stems from the fact that you didn't run the option to launch in a browser.
If you run options(shiny.launch.browser = TRUE) before launching the application, it runs properly.
