### ISSUE TITLE
Cep file download is failing

### ISSUE THREAD

**Issue by karistenneson** [openforis/accuracy-assessment#10]
I am able to download the points as a spreadsheet, but not as a cep or shapefile using the stratified area estimator design tool. However the csv will download.

**Comment by kchaase** [comment]
I am having the same problem... has there been any word on this?

**Comment by yfinegold** [comment]
Hi both,
Are you using the SEPAL version or desktop version of the application? 
The first thing to check is to make sure all the fields are complete in the 'Create a Collect Earth Project file (.cep) to start validation work' box, particularly the 'Number of operators' and 'Size of the interpretation box (in m)'. The fields should be completed by selecting a number from the dropdown list. 
![image](https://user-images.githubusercontent.com/5813936/48485811-1ee64000-e81a-11e8-9a21-6b7e28314e73.png)
