### ISSUE TITLE
Suggestions and issue

### ISSUE THREAD

**Issue by abespejo** [openforis/accuracy-assessment#8]
Hi, 

Thanks for the hard work. Some suggestions and one issue:

One issue: I have uploaded a raster and I follow all steps, the work fine, but when I click on the generation of random points, it does not work. It shows: "An error has occurred. Check your logs or contact the app author for clarification."

One suggestion: We are taking about area estimation, so using the UA or the required standard error for the OA to estimate the number of sample are not very intuitive. I would suggest that instead of UA you call it "proportion of the variable of interest" and that se of OA, is the target standard error expressed in proportion of area.

Another suggestion: Different strata will have different proportions for a variable of interest given (maybe estimated via a pilot sampling or a previous excercise). It would be good to give the flexibility to the user to define the proportions for each stratum so that we have specific variances for each variable of interest.

Final one: Also give some guidance when we have multiple variables of interest. We might be specifying the best allocation for deforestation, but it might be a poor allocation for gains (e.x. we only allocate 100 samples in the gain stratum).

**Comment by lecrabe** [comment]
Thanks  for your interest and feedback

Regarding your issue, it is probably an "instance size" issue. When you start SEPAL and want to run mid to heavy calculations, you should start a bigger instance before launching the process. I assume the map you are using is not so small ?

So, here are the steps:
- start SEPAL
- start a Terminal and when you see the choices open a higher instance (number 4 for example)
- then open the process tools, the SAED and follow the procedure.

Let us know if you encounter any further issue with this

Suggestion 1: ok, will see how we can make that clearer
Suggestion 2: yes, we have that planned in the development of the tools, good incentive that you raise the point
Suggestion 3: remember that we should keep the sampling as close as possible to "proportional", so we should avoid unbalanced sampling strategies in any case.
